dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
services: postgresql
install:
  - pip install pipenv
  - sudo apt-get -y install libenchant1c2a
  - pipenv install --dev
before_script:
  - psql -c "CREATE DATABASE will_of_the_prophets;" -U postgres
env:
  DATABASE_URL: postgresql://postgres:postgres@localhost/will_of_the_prophets/
script:
  - pipenv run black --check .
  - pipenv run isort --check-only
  - find . -iname "*.py" | xargs pipenv run pylint
  - pipenv run pytest
  - pipenv run python manage.py compilescss && git diff --no-ext-diff --exit-code
  - pipenv check
