# Generated by Django 2.1.7 on 2019-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("will_of_the_prophets", "0004_specialsquaretype_auto_move")]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("date", models.DateTimeField()),
                ("itunes_id", models.SmallIntegerField(unique=True)),
            ],
        )
    ]
